### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "test10@test.com",
    "password": "abcjdsncovnas3124710"
}

### Signin a user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "test10@test.com",
    "password": "abcjdsncovnas3124710"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/2

### Find all users with a given email
GET http://localhost:3000/auth/?email=test@test.com

### Delete a user given an id
DELETE http://localhost:3000/auth/11231321

### Update a user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
    "email": "test@test.com"
}
